{% set name = "sphinx-jsonschema" %}
{% set version = "1.19.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1a48954217c2b3c6759c89b9ddd2c8e5b668b8730564e0283b009f23932be150

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - docutils
    - jsonpointer
    - pyyaml
    - requests
    - sphinx

test:
  commands:
    - pip check
    # I need to use importlib due to the - character in the package name.
    - python -c "import importlib; importlib.import_module('sphinx-jsonschema')"
  requires:
    - pip
  # There are currently no functional unit tests ( https://github.com/lnoor/sphinx-jsonschema/issues/56 ).
    - python {{ python_min }}

about:
  home: https://github.com/lnoor/sphinx-jsonschema
  summary: Sphinx extension to display JSON Schema
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - maresb
